services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: asif
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: asif
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
