server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.Ecommerce.Order.Model.Response.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8089/api/customer
    product-url: http://localhost:8090/api/product
springdoc:
  api-docs:
    path: /api-docs
    title: My API
    description: API documentation
    version: OPENAPI_3_1
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true

