server:
  port: 8092
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.Ecommerce.Payment.Model.Request.PaymentNotificationRequest
application:
  config:
    product-url: http://localhost:8090/api/product
springdoc:
  api-docs:
    path: /api-docs
    title: Payment Service API
    description: API documentation
    version: OPENAPI_3_1
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
